on: [push]

name: Java CI with Maven and AKS Deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ vars.REGISTRY_LOGIN_SERVER }}/conoco-gateway:latest
          docker push ${{ vars.REGISTRY_LOGIN_SERVER }}/conoco-gateway:latest

      - name: 'Configure kubectl with AKS cluster'
        run: |
          az aks get-credentials --resource-group ${{ vars.RESOURCE_GROUP }} --name ${{ vars.CLUSTER_NAME }}
          
      - name: 'Deploy to AKS'
        if: always()
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/clusterissuer.yaml
          kubectl apply -f k8s/ingress.yaml
          
      - name: 'Update AKS Deployment Image'
        run: kubectl set image deployment/conoco-gateway conoco-gateway=${{ vars.REGISTRY_LOGIN_SERVER }}/conoco-gateway:latest -n ingress-basic

      - name: 'Restart Kubernetes'
        run: kubectl rollout restart deployment conoco-gateway -n ingress-basic